version: '3'
services:
  csgo-server:
    image: 367860534964.dkr.ecr.us-west-2.amazonaws.com/challenger/csgo:latest
    restart: unless-stopped
    env_file: docker-compose.env
    ports:
      - "0.0.0.0:27015:27015"
      - "0.0.0.0:27015:27015/udp"
    volumes:
      - /var/log/csgo:/csgo/csgo/logs
      - ./start.sh:/csgo/start.sh 
    networks:
      - local
  event-forwarder:
    image: 367860534964.dkr.ecr.us-west-2.amazonaws.com/challenger/csgo_event_forwarder:latest
    env_file: docker-compose.env
    restart: unless-stopped
    networks:
      local:
        aliases:
          - logging_server
          - event_forwarder
networks:
  local:
