version: 2
jobs:
  build_gameserver:
    working_directory: ~/csgo
    docker:
      - image: docker:17.11.0-ce-git
    steps:
      - checkout
      - setup_remote_docker:
          version: 17.11.0-ce
      - run:
          name: get filesystem info
          command: df
      - run:
          name: install AWS Cli
          command: |
            apk -Uuv add groff less python py-pip
            pip install awscli
      - run:
          name: Build cs:go game image
          command: |
            cd gameserver
            docker build -t 367860534964.dkr.ecr.us-west-2.amazonaws.com/challenger/csgo:${CIRCLE_SHA1} .
      - run:
          name: tag and push csgo game server image
          no_output_timeout: 1800
          command: |
            $(aws ecr get-login --no-include-email)
            docker tag 367860534964.dkr.ecr.us-west-2.amazonaws.com/challenger/csgo:${CIRCLE_SHA1} 367860534964.dkr.ecr.us-west-2.amazonaws.com/challenger/csgo:latest
            docker --log-level debug push 367860534964.dkr.ecr.us-west-2.amazonaws.com/challenger/csgo
  build_eventforwarder:
    working_directory: ~/csgo
    docker:
      - image: docker:17.11.0-ce-git
    steps:
      - checkout
      - setup_remote_docker:
          version: 17.11.0-ce
      - run:
          name: install AWS Cli
          command: |
            apk -Uuv add groff less python py-pip
            pip install awscli
      - run:
          name: Build Event forwarder Docker image
          command: |
            cd event_forwarder
            docker build -t 367860534964.dkr.ecr.us-west-2.amazonaws.com/challenger/csgo_event_forwarder:${CIRCLE_SHA1} .
      - run:
          name: tag and push event forwarder Docker image
          command: |
            $(aws ecr get-login --no-include-email)
            docker tag 367860534964.dkr.ecr.us-west-2.amazonaws.com/challenger/csgo_event_forwarder:${CIRCLE_SHA1} 367860534964.dkr.ecr.us-west-2.amazonaws.com/challenger/csgo_event_forwarder:latest
            docker push 367860534964.dkr.ecr.us-west-2.amazonaws.com/challenger/csgo_event_forwarder
  dev_gameserver_deploy:
    working_directory: ~/csgo
    docker:
      - image: circleci/python:3.6.5
    steps:
      - checkout
      - run:
          name: prep environment
          command: |
            mkdir -p ~/.ssh
            echo -n "$SSH_PRIVATE_KEY" | base64 -d > deploy_rsa
            chmod 400 deploy_rsa
            ./run_redeploy_dev.sh
  prod_gameserver_deploy:
    working_directory: ~/csgo
    docker:
      - image: circleci/python:3.6.5
    steps:
      - checkout
      - run:
          name: prep environment
          command: |
            mkdir -p ~/.ssh
            echo -n "$SSH_PRIVATE_KEY" | base64 -d > deploy_rsa
            chmod 400 deploy_rsa
            ./run_redeploy_prod.sh

  publish_tag:
    working_directory: ~/csgo
    docker:
      - image: docker:17.11.0-ce-git
    steps:
      - checkout
      - setup_remote_docker:
          version: 17.11.0-ce
      - run:
          name: install AWS Cli
          command: |
            apk -Uuv add groff less python py-pip
            pip install awscli
      - run:
          name: pull, re-tag and push images
          command: |
            $(aws ecr get-login --no-include-email)
            docker pull 367860534964.dkr.ecr.us-west-2.amazonaws.com/challenger/csgo_event_forwarder:${CIRCLE_SHA1} &
            docker pull 367860534964.dkr.ecr.us-west-2.amazonaws.com/challenger/csgo:${CIRCLE_SHA1} &
            echo "Waiting for pulls to complete"
            wait
            docker tag 367860534964.dkr.ecr.us-west-2.amazonaws.com/challenger/csgo_event_forwarder:${CIRCLE_SHA1} 367860534964.dkr.ecr.us-west-2.amazonaws.com/challenger/csgo_event_forwarder:${CIRCLE_TAG} &
            docker tag 367860534964.dkr.ecr.us-west-2.amazonaws.com/challenger/csgo:${CIRCLE_SHA1} 367860534964.dkr.ecr.us-west-2.amazonaws.com/challenger/csgo:${CIRCLE_TAG} &
            echo "Waiting for tags to complete"
            wait
            docker push 367860534964.dkr.ecr.us-west-2.amazonaws.com/challenger/csgo_event_forwarder:${CIRCLE_TAG} &
            docker push 367860534964.dkr.ecr.us-west-2.amazonaws.com/challenger/csgo:${CIRCLE_TAG} &
            echo "Waiting for pushes to complete"
            wait
            echo "Re-tag complete..."
workflows:
  version: 2
  build_and_publish:
    jobs:
      - build_gameserver:
          context: challenger_aws_prod
          filters:
            tags:
              ignore: /^v.*/
      - build_eventforwarder:
          context: challenger_aws_prod
          filters:
            tags:
              ignore: /^v.*/
      - approve_dev_gameserver_deploy:
          type: approval
          requires:
            - build_gameserver
            - build_eventforwarder
      - dev_gameserver_deploy:
          context: csgo_server_dev
          requires:
            - approve_dev_gameserver_deploy
      - approve_prod_gameserver_deploy:
          type: approval
          requires:
            - dev_gameserver_deploy
      - prod_gameserver_deploy:
          context: csgo_server_prod
          requires:
            - approve_prod_gameserver_deploy
      - publish_tag:
          context: challenger_aws_prod
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
